services:
  - type: web
    name: softpro9-backend
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json; npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 20

databases:
  - name: softpro9-db
    databaseName: softpro9_db
    user: softpro9_user
    ipAllowList: []
